/** Public reference ledger. Photographs are inspected, not redistributed as textures.
 * Coordinates below are interpreted from public wayfinding diagrams, not a survey.
 * Keep uncertainties explicit; do not invent room numbers or claim measured accuracy.
 */
// Examined but not used to assign upper-floor rooms:
// - UMIACS /images/2/2e/Inperson_IRB.png is a 517×266 full-floor diagram,
//   but its floor and room labels cannot be read reliably. The file page has
//   no caption or current usage; do not treat it as a verified Level 3 plan.
// - CBCB-quick-guide.pdf still describes BSB/AVW, not the Iribe interior.
// - NV5's Mortarr photo 52866 shows tall worktables, stools and red-footed
//   whiteboards, but identifies only “Seminar Room”, with no room number.
// The separate UMIACS Inperson_IRB_HD.png verifies the 3109A reception shape
// but is too tightly cropped to locate it within the full third-floor plan.
export const IRIBE_REFERENCES = [
  { title: 'HDR / UMD — Level 1 north-wing architectural plan', url: 'https://www.cs.umd.edu/sites/default/files/images/cs50/cs_day_program_book_v2.pdf', evidence: 'A continuous piecewise registration at the north facade, enclosed stair and central elevator aligns classroom 1207, its nine table groups and two doors, storage rooms, restrooms and Sandbox. Registering both cores prevents the first-floor offices from crossing the vertical stair shaft. The colored wayfinding classroom block had included support spaces; the architectural outline replaces it. Scale, cabinet finishes, desk furnishings and restroom stall depths remain estimates.' },
  { title: 'HDR / UMD — Level 1 perimeter offices', url: 'https://www.cs.umd.edu/sites/default/files/images/cs50/cs_day_program_book_v2.pdf', evidence: 'Seven perimeter offices and manager office 1214 follow the drawn wall and doorway layout. Furniture symbols show desks with side returns, paired guest chairs, two-chair meeting tables in the manager and northwest-end office, and a separate three-chair meeting room. Desks sit toward their return wall to preserve the access aisle. Furniture dimensions and finishes are estimates; unreadable office numbers remain unnamed.' },
  { title: 'Sandbox — support-room inventory', url: 'https://sandbox.umd.edu/wiki/index.php/Other_Rooms', evidence: 'Identifies manager office 1214, supply storage 1213 and tool storage 1209. The public emergency map fixes their locations, while the HDR plan supplies walls, doors and cabinet runs. Undocumented tools and supplies are not invented.' },
  { title: 'UMD CS — conference-room occupancies', url: 'https://helpdesk.cs.umd.edu/faq/iribe/conferencerooms.html', evidence: 'Published occupancies inform six-seat, twelve-seat, sixteen-seat and eighteen-seat layouts in the standalone modeled conference rooms. Seating positions, table dimensions and end-chair arrangement are estimates; all chair positions are checked for walking access. Room 5105 and the combined conference/huddle placeholders still need room-specific furniture and partition references.' },
  { title: 'UMIACS — Iribe conference-room equipment', url: 'https://wiki.umiacs.umd.edu/umiacs/index.php/Iribe/ConferenceRooms', evidence: 'Room-specific inventory confirms single LCD, conferencing camera and room PC in the modeled small-seminar and conference rooms; also documents the Gupta, Gobioff and Feng Peng/Xin Lei room names. Equipment dimensions and wall/table placement remain estimates. Combined conference/huddle placeholders are excluded from this equipment pass.' },
  { title: 'UMD / UMIACS — large seminar room 4105', url: 'https://wiki.umiacs.umd.edu/umiacs/index.php/Iribe/ConferenceRooms', evidence: 'Documents a projector and rear LCD, two conferencing cameras, lectern, microphone, room PC, Blu-ray and tuner in 4105. The public seminar touch-panel photograph supplies its two destinations and source controls. Hardware location, dimensions, lectern finish and mounting details are estimates; the seating arrangement remains unmodeled until a room-specific reference is available.' },
  { title: 'UMIACS — photographed AV touch panels', url: 'https://wiki.umiacs.umd.edu/umiacs/index.php/ConferenceRooms/TouchPanel', evidence: 'Photographs inform the pale-blue Crestron source selector with dark buttons. Documentation identifies tabletop cable connections, wireless keyboard/mouse and the PC behind the display. Panel artwork is redrawn as a static visual; it does not represent a live room system.' },
  { title: 'Mokhtarzada Hatchery — official workspace photograph and room address', url: 'https://www.hatchery.umd.edu/', evidence: 'The official site gives Room 2237. Its workspace photograph shows adjustable metal-frame desks, wood chairs on splayed caster legs, rolling whiteboards with red feet, dark flooring, wood wall panels and a glazed frontage. HDR Level 2 supplies two central workrooms, perimeter offices and the shared tables/window counter. The diagram marker identifies the eastern workroom as the Hatchery; exact furniture locations, dimensions and the unnumbered adjoining rooms remain estimates.' },
  { title: 'Singh Sandbox — Level 1 architectural emergency map', url: 'https://sandbox.umd.edu/wiki/images/a/ab/SandboxEmergencyMap.png', evidence: 'Public map identifies restrooms 1218 and 1219 between classroom 1207 and the Sandbox. HDR Level 1 vector drawing supplies the two room outlines, six stalls versus three stalls and three urinals, five sinks per room and wider end compartments. HDR Level 2 independently shows the same arrangement; the Level 2 wayfinding sheet registers that pair separately. Fixture placement follows the drawing; registration, metric sizes, partition heights and finishes remain estimated.' },
  { title: 'Singh Sandbox — studio floor plan', url: 'https://sandbox.umd.edu/wiki/images/f/f9/SandboxFloorPlan-Studios.jpg', evidence: 'Traced electronics, crafting, sewing, office, laser, projects, CNC and woodworking rooms around the open work area. Registered to the north Level 1 envelope; metric dimensions and door widths are estimated. The main workspace has no enclosing internal glass box.' },
  { title: 'Singh Sandbox — room and tool inventory', url: 'https://sandbox.umd.edu/wiki/index.php/Main_Page', evidence: 'Studio pages identify room numbers and equipment. Equipment photographs inform Rigol oscilloscope, Bernina sewing machine, Cricut cutter, Ultimaker printer, Tormach mill and JET drill press forms. Equipment placement and most dimensions are estimates. Current sewing label supersedes the older digital-media studio label; digital-media desks remain in the shared area.' },
  { title: 'HDR / UMD — west enclosed stair', url: 'https://www.cs.umd.edu/sites/default/files/images/cs50/cs_day_program_book_v2.pdf', evidence: 'Level 4 spread shows an enclosed switchback beside the west elevator. The model traces its shaft and doorway, with two flights and a turning landing connecting Levels 4 and 5. The Level 5 landing, metric dimensions, concrete finish and rail details are estimates; Three adjacent unnumbered room outlines, three round-table meeting rooms and the closed west lift enclosure are also traced on Level 4; meeting-room table and three-chair arrangements follow the plan symbols, with tucked-in unoccupied chairs. A/B/C are descriptive navigation names, not official room numbers. Furniture sizes and finishes are estimates. Support-room functions and the lift cab interior are not documented. Continuation to other floors and remaining west support rooms are incomplete.' },
  { title: 'HDR / UMD — communicating stairs', url: 'https://www.cs.umd.edu/sites/default/files/images/cs50/cs_day_program_book_v2.pdf', evidence: 'Level 2 and Level 4 plans show quarter-turn stairs around paired elevator shafts; the guide describes connections between pairs of floors. The Level 4–5 route is traced from the Level 4 sheet; the Level 2–3 pair is registered to the Level 2 wayfinding elevator core. Both have matching openings above. Width, tread heights, upper landings, Level 2 registration, wood finish and metal guard details are estimates.' },
  { title: 'UMD Arboretum — Margulis–Antonov Family Garden', url: 'https://arboretum.umd.edu/margulis-antonov-family-garden', evidence: 'Three public photographs document gray weathered decking, cream curved planters, timber slat benches, glass guards and planting against the auditorium brick wall and broad glazed auditorium bays. The garden record lists hostas, fragrant sumac, Japanese maples, Mexican hairgrass and yarrow. Layout follows the HDR Level 1 spread; species forms, dimensions and placements are approximated.' },
  { title: 'OpenStreetMap contributors — campus surroundings', url: 'https://www.openstreetmap.org/copyright', evidence: 'Existing campus dataset supplies real nearby building footprints, roads and waterways. Fitted to the undimensioned interior plan using four corners; alignment and flat site grade are approximate. Geometry is reused from the campus scene.' },
  { title: 'UMD Campus Plant Inventory — trees', url: 'https://services9.arcgis.com/1rOwFRpAwrxe0rBl/arcgis/rest/services/CampusPlantInventory/FeatureServer/0', evidence: 'Existing campus tree snapshot supplies nearby tree positions, heights and crown sizes. Crowns that overlap the fitted interior envelope are omitted.' },
  { title: 'UMD CS — amphitheater photograph', url: 'https://www.cs.umd.edu/sites/default/files/images/floorplans/amphitheater_photo.png', evidence: 'Timber seating tiers with illuminated nosings, brick floor and enclosure, a white circular column, and stairs beside the curtain wall. Ground-floor plan fixes the seating bank and lower entrance orientation. Drop, step dimensions and return-stair position are estimated; full adjoining stair enclosures remain incomplete.' },
  { title: 'UMD CS — public lobby photograph', url: 'https://www.cs.umd.edu/sites/default/files/images/floorplans/lobby_photo.jpg', evidence: 'Curved yellow modular sofas, blue/teal pedestal lounge chairs, round white tables and brick facing on the curved auditorium exterior. Pale panel ceiling, vertical tube pendants and paired linear ventilation slots above the lounge. Seating and fixture positions are estimated.' },
  { title: 'HDR — Breakpoint Café interior photograph', url: 'https://www.hdrinc.com/portfolio/brendan-iribe-center-computer-science-and-engineering', evidence: 'White counter with stainless plinth, glass sneeze guard, yellow backsplash, digital menu screens, coffee equipment, black refrigerated case, timber-slat canopy and white round tables with lime/gray chairs. Menu graphics are simplified; fixture dimensions and spacing are estimated.' },
  { title: 'Maryland Robotics Center — Robotics Manipulator Lab', url: 'https://facilities.robotics.umd.edu/rml/home.html', evidence: 'Room 0116 inventory and equipment portraits: two KUKA LBR iiwa arms, Baxter, Sawyer, two UR3e arms and a UR5e; panoramic photo shows yellow gantry, glass display cabinet, workbenches and glass lobby front. Workstation locations and static poses are estimates.' },
  { title: 'Maryland Robotics Center — Brin Family Aerial Robotics Lab', url: 'https://facilities.robotics.umd.edu/dronelab/equipment.html', evidence: 'Equipment and netted-area pages specify an 18-by-24-foot rectangular enclosure, 15-foot height, 1-7/8-inch nylon mesh, foam floor and 12 Vicon cameras. The overview rounds the area to 430 square feet. Photos inform the repair bench and netting; placement within the undimensioned room plan remains estimated.' },
  { title: 'Small Artifacts Lab — interior photo gallery', url: 'https://smartlab.cs.umd.edu/gallery', evidence: 'Room 0102 perimeter wood workbenches, black tool board, yellow parts drawers, desktop printers, oak storage with black worktop and sink, articulated extraction duct; dimensions and exact fixture positions are estimated from photographs.' },
  { title: 'UMD Arboretum — Reisse Park', url: 'https://arboretum.umd.edu/reisse-park', evidence: 'Rooftop planting palette, wooden deck, and waterfall fountain; official photos show the tall glass wind screens and curved planter seating.' },
  { title: 'UMD CS — room-specific furniture plans', url: 'https://www.cs.umd.edu/meeting-event-request', evidence: 'Gannon fanned desk banks; 60-inch round tables and six-chair clusters in 1207, 2107, 2207 and 1116; gallery photograph documents walnut tables, upholstered navy chairs, gray ceiling and suspended angular lights.' },
  { title: 'UMD Iribe — auditorium interior and learning spaces', url: 'https://iribe.umd.edu/innovation', evidence: 'Antonov photograph: shared desks, dark swivel seating, wood acoustic panels, angular warm lighting and three projection screens; 298-seat capacity.' },
  { title: 'UMD Residential Facilities — Level 5 architectural underlay', url: 'https://drf.umd.edu/about-us/learning-day/2026', evidence: 'Increasing contrast of the published fifth-floor wayfinding image exposes faint architectural linework: four enclosed offices immediately below room 5237, arranged in two rows, and thirteen visible perimeter offices below the conference annotation. The visible central shaft, two adjoining service-room enclosures and four unobscured middle-wing offices and the two shared-space enclosures flanking the central lift are also traced. The shared spaces remain unfurnished because their small furniture symbols are not reliable enough to count or position workstations. Furniture symbols inform the larger west office meeting area. Their equipment is not documented and is not fabricated. A coordinate-grid review refines the central island and preserves both side corridors. Partitions are traced; unreadable room numbers are omitted. Door positions, widths, desks and chairs remain estimates. Annotation boxes obscure other areas and cannot establish their partitions.' },
  { title: 'UMD Residential Facilities — Iribe floor plans', url: 'https://drf.umd.edu/about-us/learning-day/2026', evidence: 'Ground, first, second and fifth-floor wayfinding; room numbers and adjacencies.' },
  { title: 'UMD Computer Science / HDR — building guide', url: 'https://www.cs.umd.edu/sites/default/files/images/cs50/cs_day_program_book_v2.pdf', evidence: 'Ground, levels 1, 2, 4 and roof plan spreads; Level 4 north- and west-wing office partitions, end lounges, north shared workrooms, five curved-facade west workrooms and a west shared room with paired desk banks, and the service core with two restroom layouts (six stalls west; three stalls and three urinals east; five sinks per room); photographed furniture, stairs, garden and labs.' },
  { title: 'HDR — Iribe Center', url: 'https://www.hdrinc.com/portfolio/brendan-iribe-center-computer-science-and-engineering', evidence: 'Double-height lobby; two straight stair flights and curved intermediate landing around a rounded wood-clad elevator enclosure; perforated white guards, gray metal soffits, black exposed ceiling and irregular suspended linear lighting. Stair dimensions remain interpreted from photographs and undimensioned plans.' },
  { title: 'UMD — Opening a Door to Tomorrow', url: 'https://cmns.umd.edu/news-events/news/opening-door-tomorrow', evidence: 'Glass-walled labs, circular collaborative classroom tables, 5,300-square-foot Sandbox.' },
] as const;

export const INTERIOR_FIDELITY = {
  verified: ['Floor naming', 'Named public-room adjacencies', 'Lobby material palette', 'Atrium stair wrapping a wood-clad core', 'Yellow lounge seating', 'Exposed black ceilings and suspended strip lights', 'Glazed lab fronts', 'Circular teaching tables', 'Roof garden'],
  estimated: ['Level 5 named conference-room extents follow oversized wayfinding highlights where the architectural underlay is obscured; these bounds still need a clearer plan', 'West enclosed stair shaft dimensions, concrete finishes and Level 5 landing; Level 4 switchback follows the HDR plan', 'Family Garden diagram registration between the existing auditorium and corridor; planted details and dimensions', 'Exterior site registration and flat ground elevation', 'Metric dimensions interpreted from undimensioned diagrams; Level 4 west-wing alignment uses separate affine triangles to reconcile different diagram proportions', 'Furniture positions between photographed viewpoints', 'Ceiling service routes', 'Amphitheater floor drop and stair dimensions; the glass-side return is fitted around the currently registered stair shaft', 'Office and restroom finishes and equipment details not shown in photographs', 'Auditorium tier heights and row allocation', 'Gannon furniture finishes where no public interior photograph is available'],
  incomplete: [ 'Level 5 shared-space furniture beside the central lift', 'Room 5105 furniture arrangement and combined conference/huddle room partitions', 'Additional auditorium exit doors onto the Family Garden', 'Complete amphitheater stair enclosures and exterior cantilever', 'Immersive Media Design lab equipment', 'Complete Level 3 room plan', 'West stair continuation beyond Levels 4–5, lift cab and remaining west support rooms', 'Room 4105 seating layout and exact AV placement', 'Level 5 rooms hidden by wayfinding annotations and the untraced south-wing partitions', 'Nonpublic room interiors', 'Reisse Gallery photographic prints'],
};
